# Generated by Django 5.0.6 on 2024-06-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_product_is_discounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
