# Generated by Django 5.0.6 on 2024-07-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_purchase_products_alter_purchaseitem_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
